import BootstrapLoader from '@/components/bootstrap-loader';
import 'bootstrap/dist/css/bootstrap.min.css'

import localFont from "next/font/local";

const pixle = localFont({
  src: "./fonts/Pixle_Font.ttf",
  variable: "--font-pixel",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pixle.className}>
        {children}
      </body>
    </html>
  );
}
